version: '3.5'

services:
 nginx:
  build: requirements/nginx
  image: nginx:final
  ports:
  - 443:443
  networks:
  - my_network

networks:
 my_network:
  name: my_network
  driver: bridge


#essayer de ping d'un container a l'autre pour voir si le reseau fonctionne correctement
#install iputils-ping
