version: '3.5'

services:
 mariadb:
  build: requirements/mariadb
  image: mymariadb:final
  networks:
  - my_network
  env_file:
  - .env
  volumes:
  - mariadb:/var/lib/mysql
  restart: on-failure

 wordpress:
  build: requirements/wordpress
  image: wordpress:test
  networks:
  - my_network
  env_file:
  - .env
  volumes:
  - wordpress:/var/www/wordpress
  depends_on:
  - mariadb
  restart: on-failure

 nginx:
  build: requirements/nginx
  image: nginx:final
  ports:
  - 443:443
  networks:
  - my_network
  volumes:
  - wordpress:/var/www/wordpress
  depends_on:
  - wordpress
  restart: on-failure

networks:
 my_network:
  name: my_network
  driver: bridge

volumes:
 mariadb:
  name: my_mariadb_volume
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/kbrousse/data/mysql'

 wordpress:
  name: my_wordpress_volume
  driver: local
  driver_opts:
   type : 'none'
   o: 'bind'
   device: '/home/kbrousse/data/wordpress'

#essayer de ping d'un container a l'autre pour voir si le reseau fonctionne correctement
#install iputils-ping
#proteger les scripts en faisait des if -d dir au debut
